services:
  db:
    image: postgres:17
    container_name: metall_roll_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  metall_roll:
    image: metall_roll_app
    build:
      context: .
    container_name: metall_roll
    env_file:
      - .env-non-dev
    depends_on:
      - db
    #command: ["/metall_roll/docker/app.sh"]
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

volumes:
  postgresdata: