services:
  db:
    image: postgres:17
    container_name: metall_roll_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  metall_roll:
    image: metall_roll_app
    build:
      context: .
    container_name: metall_roll
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/metall_roll/docker/app.sh"]
    ports:
      - 7777:8000

volumes:
  postgresdata: